### ISSUE TITLE
The sink should take care of our master testing badges

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpituous#1]
These are the little images we display in README.md.

A log stream should be able to say that it wants to update such a test badge in its final JSON message.  It should give the id of the badge, a name text, a status text, and a symbolic status from 'passed', 'failed, 'error'.  The sink will then create that badge in a well known place.

The badges need to be served with `Cache-Control: no-cache`, see https://github.com/github/markup/issues/224

**Comment by stefwalter** [comment]
Sounds good. This should go into the status JSON as a "badge" field. In addition, because the sink is copied all over the place, and likely the badge SVG template would need to be updated over time ... lets keep the SVG short and include it in the sink file itself.

**Comment by mvollmer** [comment]
I'll have a stab at this.
