### ISSUE TITLE
refactor code to has `{extract|edit}_github_tasklist(issue_id)` or something

### ISSUE THREAD

**Issue by goern** [cockpit-project/cockpituous#160]
As a Bot developer, 
I want to use a library/framework, 
so that I can extract and modify tasks list of github issues.

**Comment by goern** [comment]
Maybe on a first attempt it operates on a string rather than a github issue itself. An external framework could take care about communication with github.

**Comment by goern** [comment]
Can we just take https://github.com/cockpit-project/cockpit/blob/master/bots/task/github.py#L331 and add a delete() and edit() ?!

**Comment by stefwalter** [comment]
Sure. Sounds good. Do you have a pull request?

**Comment by marusak** [comment]
This has been inactive for a few years now. Also I think this should be in https://github.com/cockpit-project/bots repo, not here.
It does not sound difficult to implement, but if there is no one driving this and no one needed it for 3.5 years, then I think we can just close this.

btw. now it lives here: https://github.com/cockpit-project/bots/blob/master/task/github.py#L412
