### ISSUE TITLE
The sink should maintain a general overview page

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpituous#2]
So that one can see what things are currently running, and which have recently completed.

It could do this by atomically writing little files into a dedicated directory when it starts and when it finishes.  After writing the file, it could spawn a external 'status generator' that reads all files and generates the overview page.

**Comment by martinpitt** [comment]
IMHO we shouldn't do this. The sink is complicated enough as it is, and even distributed across several hosts now. I think `bots/tests-scan -vd` for running tests gets us far enough.

@mvollmer, did you have another use case in mind?

**Comment by mvollmer** [comment]
The idea was that we can monitor what the bots are doing in a convenient place.  This is now better done in the OpenShift console, I'd say.
