### ISSUE TITLE
release: Make it easier to deal with job failures

### ISSUE THREAD

**Issue by Gundersanne** [cockpit-project/cockpituous#288]
What if when a job fails in the release runner, it sleeps indefinitely, but with the option to retry the current job or continue with the next.

~~Like it could listen for signals, SIGUSR1 for instance could be retry current job, and SIGUSR2 could be continue with the next job, skipping the failed one.~~

openshift also allows you to attach to the container like you would with `docker attach`; let's just listen for stdin input on a job failure to either retry, or skip to the next one.

**Comment by martinpitt** [comment]
Not relevant any more, releases moved to GitHub workflows.
