### ISSUE TITLE
github PR statuses are not visible in github app

### ISSUE THREAD

**Issue by allisonkarlitskaya** [cockpit-project/cockpituous#334]
Github finally has an Android app, and it's really nice, but the one thing that I'd really like to use it for the most is to check on the status of tests (when I'm at lunch or whatever).  This seems to be a supported feature of the app, but when I go to check, I see a message that says "Continuous integration not added".

I find that surprising, because we do have continuous integration.  It's apparently not being done in the way that the github app recognises it as such, however.  The feature *is* working for other projects.

See the screenshots:

Cockpit broken CI results:
![Cockpit broken CI results](https://user-images.githubusercontent.com/36541154/87778864-23070400-c82c-11ea-9f44-f1e1faeec3fe.png)

Random other project where it's working:
![Random other project where it's working](https://user-images.githubusercontent.com/36541154/87778899-31edb680-c82c-11ea-9d6a-e821edb3a12c.png)

**Comment by martinpitt** [comment]
The  official API for PR tests is https://developer.github.com/v3/repos/statuses/ , and that's what we (and semaphore, Travis, etc.) use.

**Comment by allisonkarlitskaya** [comment]
That latest update contains a changelog item:

* Issues with displaying CI status and empty repositories.

(and indeed, my "fork" of the cockpit repo is empty.)

Anyway, it seems to work now.  Clearly not our issue.  Sorry for the noise!
