### ISSUE TITLE
Retry uploading releases to GitHub

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpituous#457]
In a [recent release](https://github.com/cockpit-project/cockpit-machines/runs/5216669727?check_suite_focus=true) the curl upload fails which means the whole release job has to be retried which can take a while. Ideally the upload would be retried for ~ 3 times on failure.
```
######################################################################## 100.0%
> Uploading file: _release/source/cockpit-machines-node-261.tar.xz

#####                                                                      8.1%curl: (56) OpenSSL SSL_read: Connection reset by peer, errno 104

release-github: github api call failed
release-runner: failed code 1: release-github
```

From @martinpitt  `run_curl() in release-github`

**Comment by martinpitt** [comment]
FWIW, this has been going on for about two months now. Something in GitHub regressed, uploads became really unstable.

**Comment by martinpitt** [comment]
Oh, this was koji! I actually saw this in release-github when uploading to the GitHub release. Well, let's retry both then.

**Comment by jelly** [comment]
So I noticed curl has `--retry 3` as CLI argument but I don't think that retries for these errors but only for `Transient error means either: a timeout, an FTP 4xx response code or an HTTP 408, 429, 500, 502, 503 or 504 response code.`. There is `--retry-all-errors` but not sure if that's a good thing to use as it's marked as the "slegdehammer" approach :)

**Comment by martinpitt** [comment]
No, it was GitHub release all along. Just [failed again](https://github.com/cockpit-project/cockpit-machines/runs/5317321502?check_suite_focus=true)
