### ISSUE TITLE
Move cockpit specific Debian source package mangling from cockpituous into cockpit.git

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpituous#65]
In cockpit PR #5726 there is [a side discussion](https://github.com/cockpit-project/cockpit/pull/5726#discussion_r96218459) about cleaning up some cockpit specific bits, like:
```
   # HACK: don't install or package test assets
    sed -i -e 's/install-test-assets//' $WORKDIR/build/debian/rules
    sed -i -e '/Package: cockpit-test-assets/,/^$/d' $WORKDIR/build/debian/control
```

We'll need another quick hack to drop the -pcp package for debian testing/unstable soon.

But medium-term I think it would be nicer if the actual work was done in `release-dsc`, and `release-{debian,ubuntu}` would not unpack, mangle, and repack the .dsc again. Instead, `release-{debian,ubuntu}` could pass the target release to `release-dsc`, and that could then check if the cockpit source tree has a "mangling" script for the given release, run it, and put the right target distribution into `debian/changelog` so that we don't have to unpack/repack the .dsc again.

**Comment by martinpitt** [comment]
This is actually a bit difficult -- release-debian and release-ubuntu-ppa are not actually independent of each other, but it seems like release-ubuntu-ppa takes the exact same dsc that release-debian is producing and uploads that? This is wrong on several levels:

 * Ubuntu's `dpkg-source` is different than Debian's -- in particular, it will add `X-Launchpad-Bugs:` references to the .changes file that auto-closes referenced Launchpad bugs. There might be other differences too.

 * The Debian .dsc will have something like "unstable" as a release target in `debian/changelog`, an Ubuntu upload needs to change that. PPAs accept any value there, but for real distro uploads this needs to be changed.

 * We can't do quirks which are  specific to Debian or Ubuntu.

So all the more reason to move that work into release-dsc and call it from release-debian and release-ubuntu separately?

This is mostly a braindump and will require some more in-depth discussion with someone who is familiar with these scripts.

**Comment by stefwalter** [comment]
> But medium-term I think it would be nicer if the actual work was done in release-dsc, and release-{debian,ubuntu} would not unpack, mangle, and repack the .dsc again. Instead, release-{debian,ubuntu} could pass the target release to release-dsc, and that could then check if the cockpit source tree has a "mangling" script for the given release, run it, and put the right target distribution into debian/changelog so that we don't have to unpack/repack the .dsc again.

I guess this underscores the fact that there is no generic DSC in Debian/Ubuntu the way you can build a generic reusable SRPM? The DSC has to be distribution specific? 

If that's the ugly reality, then yes, I would be fine with building a set of DSC's and then have a way to run run release-debian or release-ppa on them. 

The important thing is to be able to build off host  for some of the actual builds where possible. That's the point of keeping the two steps separate.

**Comment by martinpitt** [comment]
> I guess this underscores the fact that there is no generic DSC in Debian/Ubuntu the way you can build a generic reusable SRPM? The DSC has to be distribution specific?

Technically you can use it for third-party repos. But people might yell at you if you put the wrong release and changelog into it, and the versioning schema is different between Debian/Ubuntu too. The other changes apply to the generated `source.changes`.

**Comment by martinpitt** [comment]
Update: Seems I misunderstood this when I was reading this in a hurry back then. The point of `release-debian` is actually to mangle the changelog/release to the target one and upload to multiple releases, so that's fine as it is. But we should generalize and remove the "Hack: Remove PCP build dependencies" for sure.
